spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/landmark
    username: postgres
    password: 25042004

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: update


    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

google:
  secret:
    key:
      path: D:/JavaProj/Hack_Server/key/credentials.json
  oauth:
    callback:
      uri: http://localhost.nip.io:8080/oauth
