# Конфигурационный файл
spring:

  # Подключение к H2 бд через jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/Hackathon
    username: postgres
    password: 25042004

  # Включение консоли
  h2:
    console:
      #enabled: false
      enabled: true

  jpa:

    #Автогенерация схемы hibernate
    #generate-ddl: false
    generate-ddl: false

    hibernate:
      #ddl-auto: none
      ddl-auto: update


    # Показываем запросы
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect